services:
  ten_agent_dev:
    image: ghcr.io/ten-framework/ten_agent_build:0.7.9
    container_name: ten_agent_dev
    platform: linux/amd64
    tty: true
    stdin_open: true
    restart: always
    network_mode: host
    volumes:
      - ./:/app
      - ${LOG_PATH}:${LOG_PATH}
      - ../.vscode/:/app/.vscode
      - ../tools/pylint/.pylintrc:/tools/pylint/.pylintrc
      - ../tools/upgrade:/tools/upgrade
    working_dir: /app
    env_file:
      - agents/examples/voice-assistant/.env
